[package]
name = "parameterized-examples"
version = "0.1.0"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Examples on how to write 'parameterized' tests."
repository = "https://github.com/foresterre/parameterized-examples"
readme = "README.md"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[workspace]
members = ["fruits"]
